- name: include jenkins repository specific variables
  include_vars: repo.yml

- name: add jenkins apt key
  apt_key:
    url: "{{ jenkins_key_url }}"
    state: present

- name: add jenkins list to apt repos
  shell: echo '{{ jenkins_repo_url }}' > /etc/apt/sources.list.d/jenkins.list
  become: yes

- name: install jenkins
  apt: name=jenkins update_cache=yes
  become: yes
