- name: add jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- name: add jenkins list to apt repos
  shell: echo 'deb http://pkg.jenkins.io/debian-stable binary/' > /etc/apt/sources.list.d/jenkins.list
  become: yes

- name: install jenkins
  apt: name=jenkins update_cache=yes
  become: yes
